apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: python-demo-app
      role: web
  template:
    metadata:
      labels:
        app: python-demo-app
        role: web
    spec:
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.web.image }}:{{ .Values.web.tag }}
          args:
          {{- range .Values.web.args }}
            - {{ quote . }}
          {{- end }}
          ports:
            - name: gunicorn
              containerPort: 8000
          resources: {{ toYaml .Values.web.resources | nindent 12 }}
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: gunicorn
              path: /
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - /bin/sh
                - -c
                - 'pidof -x gunicorn'
